ALTER TABLE taller1.designa DROP CONSTRAINT Designa;
ALTER TABLE taller1.designa DROP CONSTRAINT Designa2;
ALTER TABLE taller1.curso DROP CONSTRAINT FKcurso773804;
ALTER TABLE taller1.asigna DROP CONSTRAINT Asigna;
ALTER TABLE taller1.asigna DROP CONSTRAINT FKasigna176793;
ALTER TABLE taller1.notasest DROP CONSTRAINT FKnotasest55776;
ALTER TABLE taller1.matricula DROP CONSTRAINT Matricula;
ALTER TABLE taller1.matricula DROP CONSTRAINT Matricula2;
ALTER TABLE taller1.notasest DROP CONSTRAINT estudiante_notas;
ALTER TABLE taller1.paralelo DROP CONSTRAINT curso_paralelo;
ALTER TABLE taller1.ciclo DROP CONSTRAINT FKciclo501524;
ALTER TABLE taller1.Estudiante DROP CONSTRAINT FKEstudiante176645;
ALTER TABLE taller1.director DROP CONSTRAINT FKdirector553693;
ALTER TABLE taller1.ProfesorCurso DROP CONSTRAINT FKProfesorCu810949;
ALTER TABLE taller1.ProfesorEspecialidad DROP CONSTRAINT FKProfesorEs760316;
ALTER TABLE taller1.DesignaEspecialidad DROP CONSTRAINT DesignaEspecialidad;
ALTER TABLE taller1.DesignaEspecialidad DROP CONSTRAINT DesignaEspecialidad2;
ALTER TABLE taller1.notasest DROP CONSTRAINT Notasest;
ALTER TABLE taller1.notasest DROP CONSTRAINT Notasest2;
ALTER TABLE taller1.Materia DROP CONSTRAINT FKMateria662355;
ALTER TABLE taller1.designa ADD CONSTRAINT Designa FOREIGN KEY (paraleloIdparalelo, paraleloIdcurso) REFERENCES taller1.paralelo (Idparalelo, Idcurso);
ALTER TABLE taller1.designa ADD CONSTRAINT Designa2 FOREIGN KEY (ProfesorCursoPersonaCi) REFERENCES taller1.ProfesorCurso (PersonaCi);
ALTER TABLE taller1.curso ADD CONSTRAINT FKcurso773804 FOREIGN KEY (cicloIdciclo) REFERENCES taller1.ciclo (Idciclo);
ALTER TABLE taller1.asigna ADD CONSTRAINT Asigna FOREIGN KEY (paraleloIdparalelo, paraleloIdcurso) REFERENCES taller1.paralelo (Idparalelo, Idcurso);
ALTER TABLE taller1.asigna ADD CONSTRAINT FKasigna176793 FOREIGN KEY (aulaIdaula) REFERENCES taller1.aula (Idaula);
ALTER TABLE taller1.notasest ADD CONSTRAINT FKnotasest55776 FOREIGN KEY (valoracionIdvaloracion) REFERENCES taller1.valoracion (Idvaloracion);
ALTER TABLE taller1.matricula ADD CONSTRAINT Matricula FOREIGN KEY (paraleloIdparalelo, paraleloIdcurso) REFERENCES taller1.paralelo (Idparalelo, Idcurso);
ALTER TABLE taller1.matricula ADD CONSTRAINT Matricula2 FOREIGN KEY (EstudiantePersonaCi2) REFERENCES taller1.Estudiante (PersonaCi);
ALTER TABLE taller1.notasest ADD CONSTRAINT estudiante_notas FOREIGN KEY (estudianteCi) REFERENCES taller1.Estudiante (PersonaCi);
ALTER TABLE taller1.paralelo ADD CONSTRAINT curso_paralelo FOREIGN KEY (Idcurso) REFERENCES taller1.curso (Idcurso);
ALTER TABLE taller1.ciclo ADD CONSTRAINT FKciclo501524 FOREIGN KEY (DirectorPersonaCi) REFERENCES taller1.director (PersonaCi);
ALTER TABLE taller1.Estudiante ADD CONSTRAINT FKEstudiante176645 FOREIGN KEY (PersonaCi) REFERENCES taller1.Persona (Ci);
ALTER TABLE taller1.director ADD CONSTRAINT FKdirector553693 FOREIGN KEY (PersonaCi) REFERENCES taller1.Persona (Ci);
ALTER TABLE taller1.ProfesorCurso ADD CONSTRAINT FKProfesorCu810949 FOREIGN KEY (PersonaCi) REFERENCES taller1.Persona (Ci);
ALTER TABLE taller1.ProfesorEspecialidad ADD CONSTRAINT FKProfesorEs760316 FOREIGN KEY (PersonaCi) REFERENCES taller1.Persona (Ci);
ALTER TABLE taller1.DesignaEspecialidad ADD CONSTRAINT DesignaEspecialidad FOREIGN KEY (MateriaSigla) REFERENCES taller1.Materia (Sigla);
ALTER TABLE taller1.DesignaEspecialidad ADD CONSTRAINT DesignaEspecialidad2 FOREIGN KEY (ProfesorEspecialidadPersonaCi2) REFERENCES taller1.ProfesorEspecialidad (PersonaCi);
ALTER TABLE taller1.notasest ADD CONSTRAINT Notasest FOREIGN KEY (paraleloIdparalelo2, paraleloIdcurso2) REFERENCES taller1.paralelo (Idparalelo, Idcurso);
ALTER TABLE taller1.notasest ADD CONSTRAINT Notasest2 FOREIGN KEY (MateriaSigla) REFERENCES taller1.Materia (Sigla);
ALTER TABLE taller1.Materia ADD CONSTRAINT FKMateria662355 FOREIGN KEY (cursoIdcurso) REFERENCES taller1.curso (Idcurso);
